# Generated by Django 2.2.16 on 2020-10-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='room_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
