# Generated by Django 2.2.16 on 2020-10-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201005_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='having_tv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
