# Generated by Django 2.2.16 on 2020-10-12 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_expnses', models.IntegerField(null=True)),
                ('other_expenses', models.IntegerField(null=True)),
                ('payment_deadline', models.DateTimeField(null=True, verbose_name='支払締切日')),
                ('payment_month', models.DateTimeField(null=True, verbose_name='支払月')),
                ('is_paid', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
