# Generated by Django 2.2.16 on 2020-10-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'hogehoge', 'verbose_name_plural': 'カテゴリー'},
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='meal_expnses',
            new_name='meal_expenses',
        ),
    ]
