# Generated by Django 2.2.16 on 2021-01-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmenu',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='提供日'),
        ),
    ]
